AI_SKILLS = [
    "Python",
    "SQL",
    "Spark",
    "PyTorch",
    "TensorFlow",
    "Scikit-learn",
    "Pandas",
    "NumPy",
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing",
    "NLP",
    "Computer Vision",
    "LLM",
    "Large Language Models",
    "Fine-tuning",
    "Embeddings",
    "Vector Database",
    "Vector Databases",
    "FAISS",
    "Milvus",
    "Pinecone",
    "Weaviate",
    "RAG",
    "Retrieval-Augmented Generation",
    "LangChain",
    "LlamaIndex",
    "Transformers",
    "Hugging Face",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "GCP",
    "Airflow",
    "Kafka",
    "FastAPI",
    "Flask",
    "Git",
    "Linux"
]